version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./local_files:/usr/src/app/local_files
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - BLOB_CONTAINER_NAME=${BLOB_CONTAINER_NAME}
      - RABBITMQ_HOST=rabbitmq  
      - RABBITMQ_PORT=5672      
    depends_on:
      - rabbitmq                
    networks:
      - verilog-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - verilog-network

networks:
  verilog-network:
    driver: bridge
